export enum Entities {
    USER = 'tbl_users',
    SESSION = 'tbl_session',
    CUSTOMER = 'tbl_customer',
    ORDER = 'tbl_order',
    ORDER_PENDING = 'tbl_order_pending',
    ORDER_PRODUCTS = 'tbl_order_products',
    ORDER_DELIVERED = 'tbl_order_delivered',
    ORDER_DELIVERED_PENDING = 'tbl_order_delivered_pending',
    INVOICE = 'tbl_invoice',
    INVOICE_PENDING = 'tbl_invoice_pending',
    PAYMENT = 'tbl_payment',
    ROLES = 'tbl_roles',
    ACCESS = 'tbl_user_access',
    MENU = 'tbl_menu',
    PRODUCTS = 'tbl_products',
    PRODUCTS_PENDING = 'tbl_products_pending',
    PRODUCTS_ORDER_PENDING = 'tbl_products_ordered_pending',
    ORDER_DISTRIBUTED = 'tbl_order_distributed',
    ORDER_DISTRIBUTED_MAIN = 'tbl_order_distributed_main',
    AREA = 'tbl_area',

    EWT = 'tbl_ewt',
    PERSONNEL = 'tbl_personnel',
    HOLIDAY = 'tbl_holiday',
    PARAMETER = 'tbl_parameter'
}
