"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Entities = void 0;
var Entities;
(function (Entities) {
    Entities["USER"] = "tbl_users";
    Entities["SESSION"] = "tbl_session";
    Entities["CUSTOMER"] = "tbl_customer";
    Entities["ORDER"] = "tbl_order";
    Entities["ORDER_PENDING"] = "tbl_order_pending";
    Entities["ORDER_PRODUCTS"] = "tbl_order_products";
    Entities["ORDER_DELIVERED"] = "tbl_order_delivered";
    Entities["ORDER_DELIVERED_PENDING"] = "tbl_order_delivered_pending";
    Entities["INVOICE"] = "tbl_invoice";
    Entities["INVOICE_PENDING"] = "tbl_invoice_pending";
    Entities["PAYMENT"] = "tbl_payment";
    Entities["ROLES"] = "tbl_roles";
    Entities["ACCESS"] = "tbl_user_access";
    Entities["MENU"] = "tbl_menu";
    Entities["PRODUCTS"] = "tbl_products";
    Entities["PRODUCTS_PENDING"] = "tbl_products_pending";
    Entities["PRODUCTS_ORDER_PENDING"] = "tbl_products_ordered_pending";
    Entities["ORDER_DISTRIBUTED"] = "tbl_order_distributed";
    Entities["ORDER_DISTRIBUTED_MAIN"] = "tbl_order_distributed_main";
    Entities["AREA"] = "tbl_area";
    Entities["EWT"] = "tbl_ewt";
    Entities["PERSONNEL"] = "tbl_personnel";
    Entities["HOLIDAY"] = "tbl_holiday";
    Entities["PARAMETER"] = "tbl_parameter";
})(Entities = exports.Entities || (exports.Entities = {}));
//# sourceMappingURL=Entities.js.map